export const GET_FRIEND = 'GET_FRIEND'
export const GET_FRIEND_SUCCEEDED = 'GET_FRIEND_SUCCEEDED'
export const GET_FRIEND_FAILED = 'GET_FRIEND_FAILED'

export const ADD_FRIEND = 'ADD_FRIEND'
export const ADD_FRIEND_SUCCEEDED = 'ADD_FRIEND_SUCCEEDED'
export const ADD_FRIEND_FAILED = 'ADD_FRIEND_FAILED'

export const MOD_FRIEND = 'MOD_FRIEND'
export const MOD_FRIEND_SUCCEEDED = 'MOD_FRIEND_SUCCEEDED'
export const MOD_FRIEND_FAILED = 'MOD_FRIEND_FAILED'

export const DEL_FRIEND = 'DEL_FRIEND'
export const DEL_FRIEND_SUCCEEDED = 'DEL_FRIEND_SUCCEEDED'
export const DEL_FRIEND_FAILED = 'DEL_FRIEND_FAILED'

export const UPDATE_SSR_FRIEND = 'UPDATE_SSR_FRIEND'

export const SEARCH_FRIEND = 'SEARCH_FRIEND'
export const SEARCH_FRIEND_SUCCEEDED = 'SEARCH_FRIEND_SUCCEEDED'
export const SEARCH_FRIEND_FAILED = 'SEARCH_FRIEND_FAILED'

export const BATCH_DEL_FRIEND = 'BATCH_DEL_FRIEND'
export const BATCH_DEL_FRIEND_SUCCEEDED = 'BATCH_DEL_FRIEND_SUCCEEDED'
export const BATCH_DEL_FRIEND_FAILED = 'BATCH_DEL_FRIEND_FAILED'